LINODE_IP=192.46.230.221
DB_NAME=tugas
DB_USER=deployer
DOCKER_HUB_USERNAME=tankwanghow
IMAGE_NAME=tugas
DOCKER_CONTAINER_NAME=tugas-app
DOMAIN_NAME=192-46-230-221.sslip.io
PORT=8083
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=peggy.my.asia@gmail.com
MAIL_FROM=peggy.my.asia@gmail.com

