import Config

config :tugas, :uploads_dir, Path.expand("../priv/uploads", __DIR__)

# Configure your database
config :tugas, Tugas.Repo,
  username: "tugas",
  password: "nyhlisted",
  hostname: "localhost",
  database: "tugas_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Host used to build absolute URLs (notably the Connect-app pairing QR, which a phone
# must reach over the LAN). Defaults to localhost; export your machine's LAN IP when
# pairing the mobile app from a phone, e.g.:  DEV_HOST=192.168.1.23 mix phx.server
dev_host = System.get_env("DEV_HOST", "localhost")

config :tugas, TugasWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  url: [host: dev_host, port: 4000, scheme: "http"],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iIu5YsDXtoQsOGl/AtdYGNOlC8bYDf1X/poYwhTOjZPvEFRPUKp3pz/sBgtED84y",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tugas, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tugas, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :tugas, TugasWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/tugas_web/router\.ex$"E,
      ~r"lib/tugas_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tugas, dev_routes: true

# Pre-fetch public holidays into the ETS cache on mix phx.server boot.
config :tugas, :warm_holiday_cache, true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
